services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "i3Q1u4MYQtWSW19e13UiqA"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 2s
      timeout: 5s
      retries: 10
  
  postgres:
    image: postgres:16
    container_name: market-replay-postgres
    environment:
      POSTGRES_DB: marketreplay
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/init:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

  market-replay-api:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./
      dockerfile: src/MarketReplay.Api/Dockerfile 
    ports:
      - "5000:8080" # Swagger UI on host port 5000
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTPS_PORT=

  market-replay-ui:
    depends_on:
      kafka:
        condition: service_healthy
    build: 
      context: ./frontend
    ports:
      - "8080:80" # Frontend on host port 8080


volumes:
  postgres_data: