services:
  market-replay-api:
    build:
      context: ./
      dockerfile: src/MarketReplay.Api/Dockerfile 
    ports:
      - "5000:8080" # Swagger UI on host port 5000
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTPS_PORT=

  market-replay-ui:
    build: 
      context: ./frontend
    ports:
      - "8080:80" # Frontend on host port 8080